/** Arabic labels for the whole app. */
export const S = {
  title: 'شجرة العائلة',
  startHere: 'ابدأ بالجد الأكبر، ثم أضف أبناءه واحدًا واحدًا.',
  people: (n) => `${n} شخصًا في الشجرة`,
  oldestName: 'اسم الجد الأكبر',
  plant: 'زراعة الشجرة',
  generation: (n) => `الجيل ${n}`,
  name: 'الاسم',
  born: 'سنة الميلاد',
  male: 'ذكر',
  female: 'أنثى',
  saveName: 'حفظ الاسم',
  nameGeneration: (n) => `تسجيل الجيل ${n}`,
  addChildTo: (n) => `إضافة ابن أو ابنة إلى ${n}`,
  pickSomeone: 'اختر شخصًا من الشجرة',
  hintIdle: 'اضغط على أي اسم في الشجرة لإضافة أبناء أو زوجة.',
  selected: 'المحدد',
  marriedTo: (n) => `متزوج من ${n}`,
  marriedToAll: (names) => `متزوج من ${names.join(' و')}`,
  addAnotherWife: 'إضافة زوجة أخرى',
  motherIs: (n) => `أمه ${n}`,
  wifeCount: (n) => (n === 1 ? 'زوجة واحدة' : n === 2 ? 'زوجتان' : `${n} زوجات`),
  focus: 'تكبير المحدد',
  zoomHint: 'حرّك العجلة للتكبير، أو اضغط ضغطة مزدوجة على أي اسم.',
  leafHint: 'ورقة بلا أبناء. أضف له ابنًا فيصبح غصنًا.',
  jumpTo: 'انتقال إلى',
  removeBranch: 'حذف الفرع المحدد',
  startOver: 'البدء من جديد',
  resetView: 'إعادة الضبط',
  zoomIn: 'تكبير',
  zoomOut: 'تصغير',
  print: 'طباعة',
  savePng: 'حفظ صورة',
  saveSvg: 'حفظ ملف SVG',
  child: 'ابن/ابنة',
  wife: 'زوجة',
  husband: 'زوج',
  son: 'ابن',
  daughter: 'ابنة',
  addSon: 'إضافة ابن',
  addDaughter: 'إضافة ابنة',
  addWife: 'إضافة زوجة',
  addHusband: 'إضافة زوج',
  childName: 'اسم الابن أو الابنة',
  spouseName: 'اسم الزوج أو الزوجة',
  noChildren: 'ورقة — بلا أبناء بعد',
  children: (n) => (n === 1 ? 'ابن واحد' : `${n} أبناء`),
  remove: (n) => `حذف ${n}`,
  close: 'إغلاق',
  edit: 'تعديل',
  cancelEdit: 'إلغاء التعديل',
  saveEdit: 'حفظ التعديل',
  deleteShort: 'حذف',
  showTools: 'الأدوات',
  hideTools: 'إغلاق الأدوات',
  autoSaved: (time) => `تم الحفظ تلقائيًا ${time}`,
  autoSaveOff: 'تعذر الحفظ في هذا المتصفح. احفظ نسخة احتياطية.',
  backup: 'نسخة احتياطية',
  backupHint: 'انسخ هذا النص واحفظه عندك. للاسترجاع الصقه هنا واضغط استعادة.',
  backupCopy: 'نسخ النص',
  backupCopied: 'تم النسخ',
  backupRestore: 'استعادة من النص',
  backupSave: 'حفظ ملف',
  backupOpen: 'فتح ملف',
  backupBad: 'الملف غير صالح.',
  confirmReset: 'سيتم حذف كل الأسماء. متابعة؟',
};
